# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9610017982bc5db2d46aa380c49422064b00b914882ac6e1f32f7c3888339421ce1ca20988a9e3d69dee3ff2f82e3e812435a7c4a3ea4414820437ea388a5f08

test:
  secret_key_base: ce919684e383dbd394a80dc10d8e7260df1aad5683cbe533ca4237ceca2132f205857cb0cacfbf5f6ec3a45980c4a6b2f92b6d3bdf55f41af4711116617e1b67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
